### ISSUE TITLE
html2text::from_read panics when width is 0

### ISSUE THREAD

**Issue by nemui-i** [jugglerchris/rust-html2text#158] opened 2024-07-16 23:42 UTC
Hi,

I'm using `version = "0.12.5"`

```rust
fn main() {
    let text = "";
    html2text::from_read(text.as_bytes(), text.as_bytes().len());
    // same as 
    // html2text::from_read("".as_bytes(), 0);
    println!("Hello, world!");
}
```

panics  with `Failed to convert to HTML: TooNarrow`. I would expect an empty string instead.

Thank you for the useful library btw!

**Comment by jugglerchris** [comment] 2024-07-19 07:13
I guess it would be slightly better to not return an error when width is 0 *and* the input is empty, but it should still be an error with a width of 0 otherwise (or else it's silently losing data).

Did you mean to pass the text length as the width?  That doesn't seem like the right thing to do - the width is how wide you want the output, not directly related to the input.

On recent versions you can at least get a `Result` instead of panic:

```rust
let text = "";
html2text::config::plain()
    .string_from_read(text, width)
    .unwrap_or(String::new()); // get an empty string on error if you want
```

**Comment by nemui-i** [comment] 2024-07-20 18:35
Ah, thanks for noting the new API. So width forces `\n` warpping? What would I pass when I don't want any added wrapping?

**Comment by jugglerchris** [comment] 2024-07-20 19:24
Yes, the default settings are aimed at doing the best at showing HTML in a fixed-width terminal (that's the width you pass in to `from_read` etc.).
You can pass a large width.  Depending on what you want to do, you might want to use [raw_mode](https://docs.rs/html2text/latest/html2text/config/struct.Config.html#method.raw_mode) to avoid trying to output tables with borders.

**Comment by nemui-i** [comment] 2024-07-20 20:29
Thanks, I think just using the new Result API should be enough then.

For context: GNOME Podcasts [uses](https://gitlab.gnome.org/World/podcasts/-/blob/main/podcasts-gtk/src/widgets/show.rs?ref_type=heads#L65) html2text in a gtk4 Label to show Podcast descriptions, which can sometimes contain a little html formatting that needs to be cleared out And i noticed that podcasts without a description would make it crash.  ![screenshot of the label](https://flathub.org/_next/image?url=https%3A%2F%2Fdl.flathub.org%2Fmedia%2Forg%2Fgnome%2FPodcasts%2Fd6d904f1913b26679dc25b32e8eed368%2Fscreenshots%2Fimage-3_orig.webp&w=1920&q=75) (text under the cover image here)

Thank you for the help! feel free to close the issue if you think it works as intended.

**Comment by jugglerchris** [comment] 2024-07-20 20:51
Thanks for the information - always interesting to see where it gets used.
I think this is working as intended so I will close this issue, but feature requests (or MRs) are welcome too.

**Closed by jugglerchris** 2024-07-20 20:51 UTC
